export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const OPEN_DAILOG = 'OPEN_DAILOG';
export const CLOSE_DAILOG = 'CLOSE_DAILOG';

export const REQUEST_ITEMS_PENDING = 'REQUEST_ITEMS_PENDING';
export const REQUEST_ITMES_SUCCESS = 'REQUEST_ITEMS_SUCCESS';
export const REQUEST_ITEMS_FAILED = 'REQUEST_ITEMS_FAILED';




